const skillsData=[["Gameplay programming & core mechanics implementation","Technical Art: Niagara VFX, physics simulation, procedural animation","Multiplayer & network programming and optimization"],["Embedded software development (AVR, ESP32, Raspberry Pi)","Circuit schematic design & multi-sensor hardware integration","Robotics & mechanical design architectures (current learning target)"],["Full-stack web foundations (HTML/CSS/JS, PHP, MySQL) & Desktop development (Qt, Swing)","AI-assisted 'Vibe Coding' integration for rapid application deployment"],
["Object-oriented analysis & modular software architecture design","Version control, CI/CD pipelines & automated build scripting"],["Local deployment of open-source LLMs (Llama, Gemma, Qwen) and Gen-AI (Stable Diffusion, Z-Image, Flux) models","Model fine-tuning via LoRA & instruction datasets (current learning target)"]];
async function loadPortfolio(){return[{title:"Traffic System",image:"img/item-traffic.jpg",link:"https://youtu.be/dvXDVeAR4pk",group:"game"},{title:"HomeTeam Festival",image:"img/item-ht.jpg",link:"https://youtu.be/eGCOWdYsaIs",group:"software"},{title:"Vinpearl Digital Aquarium",image:"img/item-vpl.jpg",link:"https://youtu.be/rXQzXZUMQcg",group:"software"},{title:"Sigapore Discovery Centre",image:"img/item-sdc.jpg",link:"https://youtu.be/P-iOuhOuZew",group:"software"},{title:"Once a Pirate Show",
image:"img/item-sentosa.jpg",link:"https://youtu.be/esOCYybjYr0",group:"software"},{title:"Christmas Wonderland",image:"img/item-wonderland.jpg",link:"https://youtu.be/2mk9rQnXlUE",group:"software"},{title:"F1 Singapore GP",image:"img/item-f1.jpg",link:"https://youtu.be/HUhjqZVp6ys",group:"software"},{title:"Certis Cisco Metaverse",image:"img/item-cisco.jpg",link:"img/porfolio/cisco.jpg",group:"software"},{title:"Optical Motion Capture",image:"img/item-mocap.jpg",link:"https://youtu.be/GDGf7HmTymU",
group:"software hardware"},{title:"3D Moto",image:"img/item-moto.jpg",link:"https://youtu.be/wjcFYxk3AMU",group:"game"},{title:"Nokia Asha Competitive",image:"img/item-nokia.jpg",link:"img/porfolio/nokia.jpg",group:"game"}]}loadPortfolio().then(c=>{const b=document.getElementById("portfolio-container");b.innerHTML="";c.forEach(a=>{b.innerHTML+=`<div class="single-item col-6 col-lg-4 ${a.group}"><a class="media-lightbox" href="${a.link}" data-lightbox><div class="portfolio-wrapper"><img class="img-fluid" alt="${a.title}" src="${a.image}"><div class="item-content"><h6 class="content-title">${a.title}</h6><span class="content-more">More Info</span></div></div></a></div>`})});
async function loadBlog(){return[{title:"Vehicle AI in open world",image:"img/post-4.webp",link:"https://youtu.be/dvXDVeAR4pk",date:"21 Aug, 2024",desc:"This is showcase video for my Vehicle AI. These vehicles are performed on a open-world traffic."},{title:"Vehicle AI in complex traffic",image:"img/post-3.webp",link:"https://youtu.be/q_WkbEUwFA8",date:"20 Aug, 2024",desc:"This is showcase video for my Vehicle AI. These vehicles are performed on a small but complexed traffic."},{title:"Vehicle AI in parking area",
image:"img/post-2.webp",link:"https://youtu.be/BDaNjyj1cBM",date:"19 Aug, 2024",desc:"This is showcase video for my Vehicle AI. Navigation on offroad area. Can park into the parking lots also."},{title:"Vehicle AI with machine learning",image:"img/post-1.webp",link:"https://youtu.be/tQBoEoPzt4M",date:"18 Aug, 2024",desc:"This is an example to show how I implemented machine learning in autonomous vehicles."}]}
loadBlog().then(c=>{const b=document.getElementById("blog-container");b.innerHTML="";c.forEach(a=>{b.innerHTML+=`<div class="col-12 col-sm-8 col-lg-4"><div class="card single-post"><a class="post-img" href="${a.link}" data-lightbox><img class="card-img-top" src="${a.image}" alt="${a.title}"><span class="content-date">${a.date}</span></a><div class="card-body post-content"><a href="#0"><h5 class="card-title content-title">${a.title}</h5></a><p class="card-text content-description">${a.desc}</p></div></div></div>`})});
!function(c){c(function(){const b=document.getElementById("skillsChart").getContext("2d");let a=null;const k=new Chart(b,{type:"radar",data:{labels:["Game Development",["Hardware / IoT","Development"],"Web / App Development","System Architecture",["AI & Data","Application"]],datasets:[{label:"Current Proficiency",data:[85,40,60,40,40],backgroundColor:"rgba(233, 30, 99, 0.2)",borderColor:"rgba(233, 30, 99, 1)",pointBackgroundColor:"rgba(233, 30, 99, 1)",pointBorderColor:"#fff",pointHoverBackgroundColor:"#fff",
pointHoverBorderColor:"rgba(233, 30, 99, 1)",pointRadius:8,pointHoverRadius:12},{label:"Target Goal",data:[100,80,60,60,80],backgroundColor:"rgba(63, 81, 181, 0.1)",borderColor:"rgba(63, 81, 181, 0.8)",pointBackgroundColor:"rgba(63, 81, 181, 1)",pointBorderColor:"#fff",pointHoverBackgroundColor:"#fff",pointHoverBorderColor:"rgba(63, 81, 181, 1)",pointRadius:5}]},options:{responsive:!0,maintainAspectRatio:!0,plugins:{legend:{display:!1}},scales:{r:{grid:{color:"rgba(255, 255, 255, 0.15)"},angleLines:{color:"rgba(255, 255, 255, 0.15)"},
suggestedMin:0,suggestedMax:100,ticks:{display:!1,count:6}}},onHover:(f,d)=>{f=document.getElementById("skill-title");const g=document.getElementById("skill-details");if(d&&d.length>0){const e=d[0].index;e!=a&&(a=e,d=k.data.labels[e],Array.isArray(d)&&(d=d.join(" ")),f.innerText=d,g.innerHTML="",skillsData[e].forEach(l=>{const h=document.createElement("li");h.innerText=l;g.appendChild(h)}))}}}})})}(jQuery);!function(c){c(function(){});c(window).on("load",function(){})}(jQuery);
