async function loadPortfolio(){return[{title:"Imagine AI Studio",image:"img/item-imagine.jpg",link:"https://youtu.be/H4iaAopXIsc",desc:"A demonstration launch of Imagine AI Studio. Where you can make beatiful pictures from your imagine. You can save your images along with their prompt on your computer, or share your ideas with others...",group:"software"},{title:"IMU Motion Capture",image:"img/item-imu-mocap.jpg",link:"https://youtu.be/aLpcXS11U2c",desc:"An early test of my latest mocap concept. The system is built by integrating inertial sensors into a suit. It uses advanced fusion algorithms to ensure smooth 6-DOF tracking. It's much simpler and more cost-effective than optical...",
group:"software hardware"},{title:"Traffic System",image:"img/item-traffic.jpg",link:"https://youtu.be/OxR5_WBrPgQ",desc:"The simple traffic simulation system is written on Unreal Engine 4/5. Vehicles are populated on an open-world city map. This is also my experiment project for using machine learning technique in game AI design...",group:"game"},{title:"HomeTeam Festival",image:"img/item-ht.jpg",link:"https://youtu.be/eGCOWdYsaIs",desc:"Conceptualising, design and development of approximately 14+ multimedia and interactive experiences for the Home Team Festival 2023, from holographic avatar guide, VR scenario game, cycling game, generic touch...",
group:"software"},{title:"Madness Arena",image:"img/item-madness-arena.jpg",link:"https://youtu.be/pQ_ax2C7m1k",desc:"We are proud to announce the first ever completely in-house produced game in Singapore – from game to character design, modelling, rigging, motion capture (and move set choreography) and game development...",group:"game"},{title:"Vinpearl Digital Aquarium",image:"img/item-vpl.jpg",link:"https://youtu.be/rXQzXZUMQcg",desc:"Vinpearl Digital Aquarium, located on the island of Phu Quoc, fully conceptualized by us, from interior retrofitting to multimedia experiences, this museum features high tech features like audio guided tour, camera tracking...",
group:"software"},{title:"Sigapore Discovery Centre",image:"img/item-sdc.jpg",link:"https://youtu.be/P-iOuhOuZew",desc:"Singapore Discovery Center’s SandPlay exhibition which features conceptualization, design and development of multimedia and interactive works. Includes wall decals, conductive ink exhibit, full fledge multiplayer...",group:"software"},{title:"Once a Pirate Show",image:"img/item-sentosa.jpg",link:"https://youtu.be/esOCYybjYr0",desc:"RWT/ USS Once A Pirate Show Attraction which features 3 zones of interactive and multimedia experiences incorporated with real time 3d characters that tracks and responses to visitors clothing and movements, projection mapped...",
group:"software"},{title:"Christmas Wonderland",image:"img/item-wonderland.jpg",link:"https://youtu.be/2mk9rQnXlUE",desc:"Virtual Christmas Wonderland, built during covid lock down periods features a metaverse that is available in both mobile/ PC application. User can transverse in the metaverse to enjoy a variety of activities like carnival games...",group:"software"},{title:"F1 Singapore GP",image:"img/item-f1.jpg",link:"https://youtu.be/HUhjqZVp6ys",desc:"This project which is supported by Singapore Tourism Board is created for F1 Fan to have real experiences about the Grand Prix before the race starts. We were very honored to make such an amazing application. We played...",
group:"software"},{title:"Optical Motion Capture",image:"img/item-mocap.jpg",link:"https://youtu.be/GDGf7HmTymU",desc:"First demo of my first mocap concept. The system is built using optical tracking method. Six cheap cameras (each along with an embedded computer), are installed around the room to track the movement of markers...",group:"software hardware"},{title:"3D Moto",image:"img/item-moto.jpg",link:"https://youtu.be/wjcFYxk3AMU",desc:"My first 3D game, written on the J2ME platform to run on feature phones. The game was published on Nokia marketplace and quickly became a top trending, with 2 million downloads within the first 3 months...",
group:"game"},{title:"Nokia Asha Competitive",image:"img/item-nokia.jpg",link:"img/porfolio/nokia.jpg",desc:"I had the honor of winning first prize in a game development competition, which organized by Nokia. It recalls a memorable time in my youth, with competitions, hackathons, and prizes...",group:"game"}]}
async function loadBlog(){return[{title:"IMU Mocap test",image:"img/post-5.webp",link:"https://youtu.be/aLpcXS11U2c",date:"25 May, 2025",desc:"First demostration of my new mocap concept. Use IMUs as primary tracking method."},{title:"Vehicle AI in open world",image:"img/post-4.webp",link:"https://youtu.be/dvXDVeAR4pk",date:"21 Aug, 2024",desc:"This is showcase video for my Vehicle AI. These vehicles are performed on a open-world traffic."},{title:"Vehicle AI in complex traffic",image:"img/post-3.webp",
link:"https://youtu.be/q_WkbEUwFA8",date:"20 Aug, 2024",desc:"This is showcase video for my Vehicle AI. These vehicles are performed on a complexed traffic."},{title:"Vehicle AI in parking area",image:"img/post-2.webp",link:"https://youtu.be/BDaNjyj1cBM",date:"19 Aug, 2024",desc:"This is showcase video for my Vehicle AI. Navigation on offroad area. Can park into the parking lots also."},{title:"Vehicle AI with machine learning",image:"img/post-1.webp",link:"https://youtu.be/tQBoEoPzt4M",date:"18 Aug, 2024",
desc:"This is an example to show how I implemented machine learning in autonomous vehicles."}]}
const skillsData=[["Gameplay programming & core mechanics implementation","Technical Art: Niagara VFX, physics simulation, procedural animation","Multiplayer & network programming and optimization"],["Embedded software development (AVR, ESP32, Raspberry Pi)","Circuit schematic design & multi-sensor hardware integration","Robotics & mechanical design architectures (current learning target)"],["Full-stack web foundations (HTML/CSS/JS, PHP, MySQL) & Desktop development (Qt, Swing)","AI-assisted 'Vibe Coding' integration for rapid application deployment"],
["Object-oriented analysis & modular software architecture design","Version control, CI/CD pipelines & automated build scripting"],["Local deployment of open-source LLMs (Llama, Gemma, Qwen) and Gen-AI (Stable Diffusion, Z-Image, Flux) models","Model fine-tuning via LoRA & instruction datasets (current learning target)"]];!function(e){e(function(){})}(jQuery);
!function(e){e(function(){});e(window).on("load",function(){loadPortfolio().then(d=>{const b=document.getElementById("portfolio-container");b.innerHTML="";d.forEach(a=>{b.innerHTML+=`<div class="single-item col-6 col-lg-4 ${a.group}"><a class="media-lightbox" href="${a.link}" data-lightbox><div class="portfolio-wrapper"><img class="img-fluid" alt="${a.title}" src="${a.image}"><div class="item-content"><h6 class="content-title">${a.title}</h6><p class="content-desc">${a.desc}</p><span class="content-more">More Info</span></div></div></a></div>`});
$(".filter-control").each(()=>{var a=$("#portfolio .portfolio-section .portfolio-grid"),c=$("#portfolio .portfolio-section .filter-control li");a.imagesLoaded(function(){a.isotope({itemSelector:"#portfolio .portfolio-section .single-item",masonry:{horizontalOrder:!0}});c.on("click",function(){c.removeClass("tab-active");$(this).addClass("tab-active");var f=$(this).data("filter");a.isotope({filter:f,transitionDuration:".25s"})})})})});loadBlog().then(d=>{const b=document.getElementById("blog-container");
b.innerHTML="";d.forEach(a=>{b.innerHTML+=`<div class="col-12 col-sm-8 col-lg-4"><div class="card single-post"><a class="post-img" href="${a.link}" data-lightbox><img class="card-img-top" src="${a.image}" alt="${a.title}"><span class="content-date">${a.date}</span></a><div class="card-body post-content"><a href="#0"><h5 class="card-title content-title">${a.title}</h5></a><p class="card-text content-description">${a.desc}</p></div></div></div>`})});const k=document.getElementById("skillsChart").getContext("2d");
let g=null;const l=new Chart(k,{type:"radar",data:{labels:["Game Development",["Hardware / IoT","Development"],"Web / App Development","System Architecture",["LLMs / Gen-AI","Application"]],datasets:[{label:"Current Proficiency",data:[85,40,60,40,40],backgroundColor:"rgba(233, 30, 99, 0.2)",borderColor:"rgba(233, 30, 99, 1)",pointBackgroundColor:"rgba(233, 30, 99, 1)",pointBorderColor:"#fff",pointHoverBackgroundColor:"#fff",pointHoverBorderColor:"rgba(233, 30, 99, 1)",pointRadius:8,pointHoverRadius:12},
{label:"Target Goal",data:[100,80,60,60,80],backgroundColor:"rgba(63, 81, 181, 0.1)",borderColor:"rgba(63, 81, 181, 0.8)",pointBackgroundColor:"rgba(63, 81, 181, 1)",pointBorderColor:"#fff",pointHoverBackgroundColor:"#fff",pointHoverBorderColor:"rgba(63, 81, 181, 1)",pointRadius:5}]},options:{responsive:!0,maintainAspectRatio:!0,plugins:{legend:{display:!1}},scales:{r:{grid:{color:"rgba(255, 255, 255, 0.15)"},angleLines:{color:"rgba(255, 255, 255, 0.15)"},suggestedMin:0,suggestedMax:100,ticks:{display:!1,
count:6}}},onHover:(d,b)=>{d=document.getElementById("skill-title");const a=document.getElementById("skill-details");if(b&&b.length>0){const c=b[0].index;c!=g&&(g=c,b=l.data.labels[c],Array.isArray(b)&&(b=b.join(" ")),d.innerText=b,a.innerHTML="",skillsData[c].forEach(f=>{const h=document.createElement("li");h.innerText=f;a.appendChild(h)}))}}}})})}(jQuery);
