const TAB_STANDARD="standard",TAB_ADVANCED="advanced",SEED_RANDOM="random",SEED_MANUAL="manual";let models={},width,height,activeW=null,activeH=null,isGenerating=!1,seedMode=SEED_RANDOM,lastMeta=null,lastBlob=null,edit_id=null,eventSource=null;window.addEventListener("load",async()=>{setTab(TAB_STANDARD);setSeedMode(seedMode);randomizeSeed();updateGuidanceDisplay();onImageSizeChange();updateLibCount();checkServer()});window.addEventListener("resize",()=>resizeCanvas(activeW??width,activeH??height));
function updateGuidanceDisplay(a=null){a===null&&(a=document.getElementById("guidance-scale").value);a=parseFloat(a)*100;document.getElementById("guidance-scale").style.background=`linear-gradient(to right, var(--gold-dim) ${a}%, var(--border) ${a}%)`}function getGuidanceScale(){return parseFloat(document.getElementById("guidance-scale").value)}let currentTab=TAB_STANDARD;
function setTab(a){currentTab=a;a=a===TAB_ADVANCED;document.getElementById("tab-btn-standard").classList.toggle("active",!a);document.getElementById("tab-btn-advanced").classList.toggle("active",a);document.getElementById("tab-panel-standard").classList.toggle("active",!a);document.getElementById("tab-panel-advanced").classList.toggle("active",a)}
function getSeedValue(){if(seedMode===SEED_RANDOM)return-1;const a=parseInt(document.getElementById("seed-value").value,10);return isNaN(a)?-1:Math.max(0,Math.min(4294967295,a))}
function setSeedMode(a){seedMode=a;const b=document.getElementById("seed-btn-random"),d=document.getElementById("seed-btn-manual");a=a===SEED_RANDOM;document.getElementById("seed-value").disabled=a;(document.getElementById("btn-dice").disabled=a)?(b.classList.add("active"),d.classList.remove("active")):(d.classList.add("active"),b.classList.remove("active"))}
function randomizeSeed(){const a=Math.floor(Math.random()*4294967295);document.getElementById("seed-value").value=a;const b=document.getElementById("btn-dice");b.classList.remove("spin");b.classList.add("spin");b.addEventListener("animationend",()=>b.classList.remove("spin"),{once:!0})}
async function checkServer(){try{const a=await (await fetch(IMAGINE_SERVER,{signal:AbortSignal.timeout(3E3)})).json();if(a.server==="imagine"&&a.models.length>0){const b=document.getElementById("input-model");a.models.forEach(d=>{const c=d.alias;d=d.name;models[c]=d;b.appendChild(new Option(d,c));c===a.active&&(b.value=c)});b.disabled=!1;document.getElementById("generate-btn").disabled=!1;setStatus("Server online")}else setStatus("Server error","error")}catch{setStatus("Server offline","error")}}
function setStatus(a,b=null){document.getElementById("status-text").textContent=a;a=document.getElementById("status-dot");a.className="status-dot";b&&a.classList.add(b)}function setGenerationStatus(a){isGenerating=document.getElementById("generate-btn").disabled=a}function setProgress(a){document.getElementById("progress-bar").style.width=a+"%";document.getElementById("progress-label").textContent=a+"%"}
function showSaveBtn(a){const b=document.getElementById("btn-save");b.style.display=a?"flex":"none";b.disabled=!1;b.classList.remove("saved");b.textContent="";a&&(b.innerHTML='<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg>Save')}
async function startGeneration(){const a=document.getElementById("input-prompt").value.trim(),b=document.getElementById("input-negative").value.trim(),d=document.getElementById("input-model").value,c=document.getElementById("input-quality").value,e=document.getElementById("output-image"),f=document.getElementById("loading-overlay"),g=document.getElementById("empty-state");if(!a)return alert("Please enter a prompt!");const k=getSeedValue();setGenerationStatus(!0);lastBlob=lastMeta=null;showSaveBtn(!1);
activeW=width;activeH=height;resizeCanvas(width,height);e.classList.remove("visible");e.style.display="none";g.style.display="none";f.classList.add("active");setProgress(0);setStatus("Sending request…","busy");try{const l=getGuidanceScale(),n=(await (await fetch(`${IMAGINE_SERVER}/submit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:a,negative:b,width,height,model:d,quality:c,seed:k,guidance:l})})).json()).task_id;eventSource&&eventSource.close();eventSource=
new EventSource(`${IMAGINE_SERVER}/stream/${n}`);eventSource.onmessage=function(h){h=JSON.parse(h.data);if(h.status==="pending")setStatus(`Queue position: ${h.position}`,"busy"),setProgress(0);else if(h.status==="processing")setStatus(`Generating… ${h.progress}%`,"busy"),setProgress(h.progress);else if(h.status==="completed"){f.classList.remove("active");setProgress(100);setStatus("Done");e.src="data:image/jpeg;base64,"+h.image;e.style.display="block";requestAnimationFrame(()=>e.classList.add("visible"));
let m=Date.now();lastMeta={id:m,prompt:h.prompt,negative:h.negative,model:h.model,size:h.size,quality:h.quality,seed:h.seed,guidance:h.guidance,time:(new Date).toISOString()};lastBlob={id:m,data:h.image};showSaveBtn(!0);seedMode===SEED_RANDOM&&(document.getElementById("seed-value").value=h.seed);eventSource.close();setGenerationStatus(!1)}else h.status==="failed"&&(f.classList.remove("active"),g.style.display="flex",setStatus("Generation failed","error"),setProgress(0),eventSource.close(),setGenerationStatus(!1))};
eventSource.onerror=function(){f.classList.remove("active");g.style.display="flex";setStatus("Disconnected","error");eventSource.close();setGenerationStatus(!1);activeH=activeW=null;resizeCanvas(activeW??width,activeH??height)}}catch(l){f.classList.remove("active"),g.style.display="flex",setStatus("API error: "+l.message,"error"),setGenerationStatus(!1),activeH=activeW=null,resizeCanvas(activeW??width,activeH??height)}}
function onImageSizeChange(){const a=document.getElementById("input-aspect").value;[width,height]=a.split("x");activeW===null&&resizeCanvas(width,height)}function resizeCanvas(a,b){var d=document.querySelector(".panel-right");const c=document.getElementById("canvas-frame");d=Math.min(1,(d.clientWidth-64)/a);c.style.width=Math.round(a*d)+"px";c.style.height=Math.round(b*d)+"px"}const DB_NAME="imagine_db",DB_VERSION=1,STORE_META="meta",STORE_BLOB="blobs";let _db=null;
function openDB(){return _db?Promise.resolve(_db):new Promise((a,b)=>{const d=indexedDB.open(DB_NAME,DB_VERSION);d.onupgradeneeded=c=>{c=c.target.result;c.objectStoreNames.contains(STORE_META)||c.createObjectStore(STORE_META,{keyPath:"id"}).createIndex("time","time");c.objectStoreNames.contains(STORE_BLOB)||c.createObjectStore(STORE_BLOB,{keyPath:"id"})};d.onsuccess=c=>{_db=c.target.result;a(_db)};d.onerror=c=>b(c.target.error)})}
async function dbGetAllMeta(){const a=await openDB();return new Promise((b,d)=>{const c=a.transaction(STORE_META,"readonly").objectStore(STORE_META).getAll();c.onsuccess=()=>b(c.result.sort((e,f)=>f.id-e.id));c.onerror=e=>d(e.target.error)})}async function dbCount(){const a=await openDB();return new Promise((b,d)=>{const c=a.transaction(STORE_META,"readonly").objectStore(STORE_META).count();c.onsuccess=()=>b(c.result);c.onerror=e=>d(e.target.error)})}
async function dbSave(a,b){const d=await openDB();return new Promise((c,e)=>{const f=d.transaction([STORE_META,STORE_BLOB],"readwrite");f.objectStore(STORE_META).put(a);f.objectStore(STORE_BLOB).put(b);f.oncomplete=c;f.onerror=g=>e(g.target.error)})}async function dbGetBlob(a){const b=await openDB();return new Promise((d,c)=>{const e=b.transaction(STORE_BLOB,"readonly").objectStore(STORE_BLOB).get(a);e.onsuccess=()=>d(e.result?.data??null);e.onerror=f=>c(f.target.error)})}
async function dbDelete(a){const b=await openDB();return new Promise((d,c)=>{const e=b.transaction([STORE_META,STORE_BLOB],"readwrite");e.objectStore(STORE_META).delete(a);e.objectStore(STORE_BLOB).delete(a);e.oncomplete=d;e.onerror=f=>c(f.target.error)})}
async function dbClear(){const a=await openDB();return new Promise((b,d)=>{const c=a.transaction([STORE_META,STORE_BLOB],"readwrite");c.objectStore(STORE_META).clear();c.objectStore(STORE_BLOB).clear();c.oncomplete=b;c.onerror=e=>d(e.target.error)})}async function dbGetMeta(a){const b=await openDB();return new Promise((d,c)=>{const e=b.transaction(STORE_META,"readonly").objectStore(STORE_META).get(a);e.onsuccess=()=>d(e.result??null);e.onerror=f=>c(f.target.error)})}
async function loadEntry(a){if(!isGenerating){try{var b=await dbGetMeta(a)}catch{return}document.getElementById("input-prompt").value=b.prompt??"";document.getElementById("input-negative").value=b.negative??"";b.size&&(document.getElementById("input-aspect").value=b.size,[activeW,activeH]=b.size.split("x"),onImageSizeChange());b.quality!==void 0&&(document.getElementById("input-quality").value=b.quality);if(b.model){var d=document.getElementById("input-model");for(const c of d.options)if(c.value===
b.model){d.value=b.model;break}}b.guidance!==void 0&&(document.getElementById("guidance-scale").value=b.guidance,updateGuidanceDisplay(b.guidance));d=b.seed!==void 0&&b.seed>=0?b.seed:0;document.getElementById("seed-value").value=d;setSeedMode(!1);edit_id=a;try{const c=await dbGetBlob(a);if(c){const e=document.getElementById("output-image");e.src="data:image/jpeg;base64,"+c;e.style.display="block";e.classList.add("visible");document.getElementById("empty-state").style.display="none";lastMeta={...b};
lastBlob={id:b.id,data:c};showSaveBtn(!1);resizeCanvas(activeW??width,activeH??height)}}catch(c){console.error("Error loading image blob:",c)}setTab(TAB_STANDARD);closeLibrary()}}function editImage(){if(lastBlob&&lastBlob.data)try{sessionStorage.setItem("edit_image_data",lastBlob.data),window.open("edit.html","_self")}catch(a){alert("Could not open editor: Image data too large for session storage.")}}
const imgObserver=new IntersectionObserver(a=>{a.forEach(async b=>{if(b.isIntersecting){var d=b.target;b=+d.dataset.imgId;imgObserver.unobserve(d);try{const c=await dbGetBlob(b);if(c){const e=new Image;e.onload=()=>{d.src=e.src;d.classList.remove("skeleton")};e.onerror=()=>d.classList.remove("skeleton");e.src="data:image/jpeg;base64,"+c}else d.classList.remove("skeleton")}catch{d.classList.remove("skeleton")}}})},{rootMargin:"120px"});
async function updateLibCount(){try{document.getElementById("lib-count").textContent=await dbCount()}catch{}}
async function saveToLibrary(){if(lastMeta&&lastBlob){var a=!1;if(edit_id!==null)try{var b=await dbGetMeta(edit_id);b&&(a=b.prompt===lastMeta.prompt&&b.negative===lastMeta.negative&&b.model===lastMeta.model&&b.size===lastMeta.size&&b.seed===lastMeta.seed)&&(lastMeta.id=edit_id,lastBlob.id=edit_id)}catch(f){console.error("Error checking edit_id:",f)}b=document.getElementById("btn-save");b.disabled=!0;var d=document.getElementById("output-image"),c=document.querySelector(".btn-library");if(d&&c&&d.src){const f=
d.getBoundingClientRect();var e=c.getBoundingClientRect();const g=document.createElement("img");g.src=d.src;g.className="fly-to-lib";Object.assign(g.style,{left:f.left+"px",top:f.top+"px",width:f.width+"px",height:f.height+"px",opacity:"1",transition:"none"});document.body.appendChild(g);d=e.left+e.width/2;e=e.top+e.height/2;g.style.transition="left 0.65s cubic-bezier(0.4,0,0.2,1), top 0.65s cubic-bezier(0.4,0,0.2,1), width 0.65s cubic-bezier(0.4,0,0.2,1), height 0.65s cubic-bezier(0.4,0,0.2,1), opacity 0.55s 0.1s ease, border-radius 0.5s ease";
g.style.left=d-11+"px";g.style.top=e-11+"px";g.style.width="22px";g.style.height="22px";g.style.opacity="0";g.style.borderRadius="50%";setTimeout(()=>{c.classList.remove("arrived");c.classList.add("arrived");c.addEventListener("animationend",()=>c.classList.remove("arrived"),{once:!0});g.remove()},680)}try{await dbSave(lastMeta,lastBlob),edit_id=null,await updateLibCount(),b.classList.add("saved"),b.innerHTML=`<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="20 6 9 17 4 12"/></svg>${a?
"Updated":"Saved"}`}catch(f){b.disabled=!1,alert("Could not save image: "+f.message)}}}async function openLibrary(){await renderLibrary();document.getElementById("lib-backdrop").classList.add("open");document.body.style.overflow="hidden"}function closeLibrary(){document.getElementById("lib-backdrop").classList.remove("open");document.body.style.overflow=""}function onBackdropClick(a){a.target===document.getElementById("lib-backdrop")&&closeLibrary()}
async function clearLibrary(){confirm("Delete all saved images? This cannot be undone.")&&(await dbClear(),await updateLibCount(),await renderLibrary())}async function deleteEntry(a){confirm("Delete this image? This cannot be undone.")&&(await dbDelete(a),await updateLibCount(),await renderLibrary())}async function downloadEntry(a){try{const d=await dbGetBlob(a);if(d){var b=document.createElement("a");b.href="data:image/jpeg;base64,"+d;b.download=`imagine_${a}.jpg`;b.click()}}catch{}}
async function renderLibrary(){imgObserver.disconnect();const a=document.getElementById("lib-grid"),b=document.getElementById("lib-toolbar-info");a.innerHTML='<div class="lib-empty" style="opacity:1"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" style="animation:spin 1s linear infinite"><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg></div>';let d;try{d=await dbGetAllMeta()}catch{d=[]}b.textContent=d.length===0?"0 saved images":d.length===1?"1 saved image":
`${d.length} saved images`;d.length===0?a.innerHTML='<div class="lib-empty"><svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" opacity="0.4"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>No images saved yet</div>':(a.innerHTML=d.map(c=>{const e=escHtml(c.prompt),f=models[c.model]??c.model,g=["Fast",
"Balanced","Quality"][c.quality]??c.quality,k=(new Date(c.time)).toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"});return`<div class="lib-card"><div class="lib-card-img-wrap"><img class="lib-card-img skeleton" data-img-id="${c.id}"><div class="lib-card-tags-overlay"><span class="lib-tag">${f}</span><span class="lib-tag">${c.size}</span><span class="lib-tag">${g}</span></div><div class="lib-card-meta"><div class="lib-card-prompt">${e}</div><div class="lib-card-date">${k}</div></div></div><div class="lib-card-actions"><button class="lib-btn load" onclick="loadEntry(${c.id})">Load</button><button class="lib-btn" onclick="downloadEntry(${c.id})">Download</button><button class="lib-btn delete" onclick="deleteEntry(${c.id})">Delete</button></div></div>`}).join(""),
a.querySelectorAll(".lib-card-img[data-img-id]").forEach(c=>imgObserver.observe(c)))}function escHtml(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")};
